apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {“acme.local”: ["10.254.0.1","172.17.0.1","192.168.1.1"]}
  upstreamNameservers: |
    ["10.0.2.3",“8.8.8.8”, “8.8.4.4”]
