kind: Service
apiVersion: v1
metadata:
  name: nginx-prod-dep
  labels:
    app: nginx-prod-dep
spec:
  selector:
    app: nginx-prod-dep
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-prod-dep
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-prod-dep
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports: 
        - containerPort: 80
